name: Count Custom Emojis

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 9 * * '

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U discord.py
    - name: Test Applicaion
      if: github.event_name == 'push'
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GUILD_ID: ${{ secrets.TEST_GUILD_ID }}
        CHANNEL_ID: ${{ secrets.TEST_CHANNEL_ID }}
      run: python ci.py $BOT_TOKEN $GUILD_ID $CHANNEL_ID
    - name: Run Applicaion
      if: github.event_name == 'schedule'
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: python ci.py $BOT_TOKEN $GUILD_ID $CHANNEL_ID
    
